### ISSUE TITLE
about token and cookie

### ISSUE THREAD

**Issue by kambleaa007** [dstepanets/YouPassed#1]
I like your code written in file,
SecurityConfig.java
i like .logout().sessionInvalidate().cookie()

is there any alternative to take token from cookie jsession like extract it, and put as jwt token for http heder Authorization : Bearer TOKEN

**Comment by dstepanets** [comment]
Hi, Ashish! Thank you for your interest. I am not sure what you are trying to achieve, but maybe check these threads: 
https://stackoverflow.com/questions/38341114/spring-security-cookie-jwt-authentication
https://codereview.stackexchange.com/questions/167462/spring-jwt-authentication-using-cookies
Frankly, I don't have the answer right away, so good luck in your search!

**Comment by kambleaa007** [comment]
Thanks for quick response
